is_v100: false

image_finetune: true

output_dir: "outputs"
pretrained_model_path: "huggingface_models/runwayml/stable-diffusion-v1-5"

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  rgb_root: dataset/train_data/train/org
  pose_root: dataset/train_data/train/pose
  sil_root: dataset/train_data/train/sil
  sample_size: 256
  text_prompts:
    - "passerby"
    - "neature passerby"
    - "a photo of passerby"
    - "a photo of a pedestrian"
    - "a photo of a person walking"
    - "a photo of a person walking in the street"
    - "person"
    - "person walking"
    - "pedestrian"




validation_data:
  prompts:
    - "a photo of passerby, best quality, highres"
  num_inference_steps: 25
  guidance_scale: 8.

trainable_modules:
  - "."

unet_checkpoint_path: ""

learning_rate:    1.e-5
train_batch_size: 8

max_train_epoch:      20
max_train_steps:      -1
checkpointing_epochs: -1
checkpointing_steps:  5000

validation_steps:       1000
validation_steps_tuple: [2]

global_seed: 347
mixed_precision_training: true
enable_xformers_memory_efficient_attention: false

is_debug: False
