is_v100: false

image_finetune: false

output_dir: "outputs"
pretrained_model_path: "huggingface_models/runwayml/stable-diffusion-v1-5"

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 32
    temporal_attention_dim_div         : 1
    zero_initialize                    : true

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  rgb_root: dataset/train_data/train/org
  pose_root: dataset/train_data/train/pose
  sil_root: dataset/train_data/train/sil
  sample_size: 512
  frame_number: 4
  interval: 4
  text_prompts:
    - "passerby"
    - "realistic passerby"
    - "a video of passerby"
    - "a video of a pedestrian"
    - "a video of a person walking"
    - "person"
    - "person walking"
    - "pedestrian"

validation_data:
  prompts:
    - "passerby, best quality"
  mask_path: dataset/train_data/test/sil/Delhi/000051.pkl
  image_path: dataset/train_data/test/org/Delhi/000051.pkl
  num_inference_steps: 25
  guidance_scale: 8.
  context_overlap: 1

trainable_modules:
  - "motion_modules."

unet_checkpoint_path: ""

learning_rate:    1.e-5
train_batch_size: 1

max_train_epoch:      5
max_train_steps:      -1
checkpointing_epochs: 1
checkpointing_steps:  -1

validation_steps:       2000
validation_steps_tuple: [2, 500]

global_seed: 347
mixed_precision_training: true
enable_xformers_memory_efficient_attention: False

is_debug: False

rank: 4

pre_trained_2d_unet_path: "outputs/image_finetune_inpaint_a100-2024-04-08T16-25-55/checkpoints/checkpoint-epoch-45.ckpt"

inference_frame_number: 8
motion_module_path: huggingface_models/v3_sd15_mm.ckpt
mm_zero_proj_out: False
