is_v100: True

image_finetune: false

output_dir: "outputs"
pretrained_model_path: "huggingface_models/runwayml/stable-diffusion-v1-5"

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : False
  unet_use_temporal_attention    : false

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 24
    temporal_attention_dim_div         : 1
    zero_initialize                    : true


noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  rgb_root: dataset/GaitLU_img/train/org
  pose_root: dataset/GaitLU_img/train/pose
  sil_root: dataset/GaitLU_img/train/sil
  sample_size: 256
  frame_number: 8
  interval: 4
  text_prompts:
    - "passerby"
    - "realistic passerby"
    - "a video of passerby"
    - "a video of a pedestrian"
    - "a video of a person walking"
    - "person"
    - "person walking"
    - "pedestrian"

validation_data:
  prompts:
    - "person, best quality, realistic"
  mask_path: dataset/train_data/GaitLU_img/test/mask/Delhi/000051
  image_path: dataset/train_data/GaitLU_img/test/org/Delhi/000051
  pose_path: dataset/train_data/GaitLU_img/test/pose/Delhi/000051
  num_inference_steps: 25
  guidance_scale: 8.
  deliate_mask: False

trainable_modules: null
  # - "motion_modules."
  # - "attn_temp"
  # - "norm_temp"

unet_checkpoint_path: ""

learning_rate:    1.e-5
train_batch_size: 2

max_train_epoch:      10
max_train_steps:      -1
checkpointing_epochs: 5
checkpointing_steps:  -1

validation_steps:       2000
validation_steps_tuple: [1, 500]

global_seed: 347
mixed_precision_training: true
enable_xformers_memory_efficient_attention: False

is_debug: False

rank: 4

pre_trained_2d_unet_path: "outputs/cse_logs/stage1_lora/diffusion_pytorch_model.bin"

inference_frame_number: 32